version: "3.8"
services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
  
  backend:
    build: .
    image: backend-image:latest
    container_name: backend-container
    command: uvicorn app:app --host 0.0.0.0 --port 80 --reload
    environment:
      ENV: DEV
      DATABASE_URL: postgresql+psycopg2://postgres:1234@database:5432/test
      PYTHONDONTWRITEBYTECODE: 1
    ports:
      - "8000:80"
    depends_on:
      - database
    volumes:
      - ./src:/src
      - ./tests:/tests
      - ./migrations:/migrations