version: "3.8"
services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
  
  backend:
    build: .
    image: backend-image:latest
    container_name: backend-container
    command: uvicorn app:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "8000:80"
    depends_on:
      - database
    volumes:
      - ./src:/app